### ISSUE TITLE
Problem with Choice(s) when using multi-languages Dataverse

### ISSUE THREAD

**Issue by JMG74** [MscrmTools/Javista.AttributesFactory#24]
Hi Tanguy and everyone!

We noticed a very annoying behavior of the data dictionary regarding the Choice(s) (Option sets) when multi-languages is involved. 

First, here are some information about our context : we're developing multi-language applications (French and English) using a Dataverse having French as its primary language and English as secondary.
When updating an existing Choise(s) (for example when adding a value) the English translations are deleted for all already existing values :-(

In our understanding, the Attribute Factory seems not considering multi-languages; this is just like if it were working only with the primary language of the Dataverse.  Is it right? 

Would it be possible to enhance the data dictionary to allow providing all the multi-languages texts in all the managed languages? For example by entering a text in a cell as a list of pairs containing the language code and the corresponding text.

Looking forward for your feedback and many thanks in advance ! 
Joyeux Noël et excellentes fêtes de fin d'année.

**Comment by MscrmTools** [comment]
Hi @JMG74, I can handle multiple languages but that would imply using a JSON structure to put all languages. I'm wondering if it's not too technical here.
The structure would be something like the following:

```
[
  { 
    "value": 1,
    "labels":[
    {
      "lcid":1033,
      "label":"Mr",
      "description":"Mr desc"
    },
    {
      "lcid":1036,
      "label":"Monsieur",
      "description":"Desc Monsieur"
    }
    ]
  },
 { 
    "value": 2,
    "labels":[
    {
      "lcid":1033,
      "label":"Mrs",
      "description":"Mrs desc"
    },
    {
      "lcid":1036,
      "label":"Madame",
      "description":"Desc Madame"
    }
    ]
  }
]
```

**Comment by MscrmTools** [comment]
To start fixing this issue, I can also avoid to recreate labels and use existing ones to update only the base language.

**Comment by JMG74** [comment]
Hi !

Thanks for your reply and all the best for the new year :-) 

I agree with you that your first proposal would be the "ideal" solution but also the more technical one.

The second one would be easier to use and would fit better to our multi-languages context because we are using the default tools provided by the PowerPlatform to extract the text elements to translate and to re-import them after translation.
In this context, it is totally acceptable to deal only with the basic language in the AttributesFactory but at the same, the other text elements already in our Dataverse for the choice items in the other languages must be preserved.

Many thanks in advance and all the best.

**Comment by MscrmTools** [comment]
Latest version published yesterday should handle labels correctly.
Please give it a try and tell me if it fits your needs

**Comment by JMG74** [comment]
Hi Team,

All the best for this new year !! and thanks for your update.

I tried to test the latest version (v1.2023.1.22) according to the multilanguages aspects but I felt into many other errors 
when dealing with fields of type "Choice".  This is just like if there were regressions.

Please find below the tests I performed and their results :

In a table, I attempted to create a new field of type "Choice" with the following variations :

1. Create a new field with a local Choice (values in col P and col Q is empty)
==> **ERROR** : Object reference not set to an instance of an object.
2. Create a new field with a global choice that does not already exists (values in col P and schema name in col Q)
==> **ERROR** : Object reference not set to an instance of an object.
3. Create a new field with a global choice (col Q) that already exists:
a) no values in col P:
&nbsp;&nbsp;&nbsp;&nbsp;Expected behaviour: new field is created and properly linked to global Choice.
&nbsp;&nbsp;&nbsp;&nbsp;Result : field is created and properly related to the existing Global Choice
&nbsp;&nbsp;&nbsp;&nbsp;but there is a **problem in Dataverse** : the display name of the new field is **WRONG**;
&nbsp;&nbsp;&nbsp;&nbsp;It is currently overwritten with the description!
b) col P with same values as existing global choice, col Q with schema name of the existing global choice:
&nbsp;&nbsp;&nbsp;&nbsp;Expected behaviour: Field is created and global Choice values are not changed.
&nbsp;&nbsp;&nbsp;&nbsp;==> **ERROR** : Object reference not set to an instance of an object.
c) col P with different values than current global Choice, col Q with schema name of the existing global choice:
&nbsp;&nbsp;&nbsp;&nbsp;Expected behaviour: Field is created and global Choice values are updated.
&nbsp;&nbsp;&nbsp;&nbsp;==> **ERROR** : Object reference not set to an instance of an object.

Many thanks in advance for your help and best regards.
JM

**Comment by MscrmTools** [comment]
@JMG74 This version should fix the issue. Can you test it (this is a more recent version than the one in the other issue with descriptions)
[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/10437380/Javista.AttributesFactory.zip)

**Comment by MscrmTools** [comment]
@JMG74 same answer than for the other issue. Latest published version should fix your errors

**Comment by JMG74** [comment]
Sorry but still impossible to create a local choice. Please, find below the values used for this test:
![img1](https://user-images.githubusercontent.com/13162921/214075750-a05e2ef7-8f40-4682-8d52-f06c1bbb2291.png)
![img2](https://user-images.githubusercontent.com/13162921/214075804-69200936-2027-4dfd-b9a6-53f1380a9fbf.png)

I'm still getting the same error:
![img3](https://user-images.githubusercontent.com/13162921/214075839-6e528236-f71d-4b18-a18a-863994c1d7e3.png)

Due to this error, I did not even tried to test the other cases.

Thanks in advance. Best regards.

**Comment by MscrmTools** [comment]
Can you precise what is your version number? I'm not reproducing this error

But I can see the status is `Update Error`. Are you sure it was not an existing optionset? Even with updating the one I just created, I do not reproduce this

**Comment by JMG74** [comment]
Version is : 1.2023.1.24 (the latest available version from XrmToolBox ToolLibrary)

Yes, I confirm that the choice I'm trying to create does not exist.

I've just tested again from a brand new dictionary that I got from button "Get template" and I'm getting the same error.

**Comment by JMG74** [comment]
Hi ! I guess I've understood why you are not able to reproduce the problem I mentioned !!
The error occurs only when descriptions are added to choice's values.
Some example to illustrate:
1. If the choice values are:
287030001:Value 1
287030002:Value 2
287030003:Value 3
It's **working fine** (for local choice and global choice, either they are created or updated).

1. If I add **description** to the choice values:
287030001:Value 1:**Description 1**
287030002:Value 2:**Description 2**
287030003:Value 3:**Description 3**
I'm getting the **error** "Object reference not set to an instance of an object".

**Comment by MscrmTools** [comment]
Thank you! Fixed!

**Comment by MscrmTools** [comment]
you're welcome :)
